version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    networks:
      - startup-network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key
      - DB_NAME=startup_db
      - DB_USER=startup_user
      - DB_PASSWORD=startup_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - startup-network

  # PostgreSQL
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=startup_db
      - POSTGRES_USER=startup_user
      - POSTGRES_PASSWORD=startup_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - startup-network

  # Redis
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - startup-network

  # Nginx (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - frontend
      - backend
    networks:
      - startup-network

volumes:
  postgres_data:
  redis_data:

networks:
  startup-network:
    driver: bridge